### ISSUE TITLE
Dependency-Update

### ISSUE THREAD

**Issue by nOester** [swisstopo/swissgeol-viewer-app#1337]
**Beschreibung**
Die letzte Akualisierung Software-Bibliotheken (Dependencies) wurde im Juni 2024 durchgeführt.
Daher sollen die Dependencies aktualisiert werden, so dass die Applikation keine Sicherheitslücken aufweist und lauffähig ist. 
Es soll geprüft werden, wie Mit Updates umgegangen wird, die zu Breaking changes führen
Ein automatischer Dependency-Checker (z.B. Renovate) soll aktiviert werden. 

**ToDos**
- [x] Dependency-Checker aktivieren
- [x] Liste der relevanten Updates erstellen
- [x] Prüfen, welche Aktualisierungen zu Breaking Changes führen
- [x] Mit @nOester  weiteres Vorgehen entscheiden

Folgetaks
- [x] Dependencies aktualisieren

**Acceptance Criteria**
- [ ] Dependency-Checker ist aktiviert
- [ ] Liste der relvanten Updates und möglicher Breaking Changes ist erstellt
- [ ] Das weitere Vorgehen ist definiert

**Comment by daniel-va** [comment]
@nOester Scheint soweit zu funktionieren. Wir haben auch bereits einen ersten Report erhalten. Von mir aus reicht das.
