### ISSUE TITLE
Suche anpassen

### ISSUE THREAD

**Issue by nOester** [swisstopo/swissgeol-viewer-app#1338]
**Beschreibung**
Das bestehende Suchfeld im Header der Applikation soll angepasst werden. 
Die Auswahl eines Suchergebnisses soll von zweimaligem "Enter"-drücken auf ein-mailiges "Enter"-drücken reduziert werden. Der Rest des bestehenden Verhaltens bleibt unverändert.

Folgendes Verhalten soll erreicht werden:
1. Such-Begriff eingeben
2. Einmaliges "Enter"-drücken --> Der erste Eintrag in den Suchergebnissen wird ausgewählt. Je nach Typ des Suchergebnisses (Ort, Koordinate, Datensatz) wird der Fokus der Kamera auf den selektierten Ort  bzw. Koordinate verschoben oder der selektierte Datensatz an oberster Position in den Datenkatalog eingefügt und angezeigt.

Wenn mit der Maus oder den Pfeiltasten ein Suchergebnis aus der Liste ausgewählt wird, soll:
- bei Ort oder Koordinate: Der Maus-Click bzw. das "Enter-drücken" soll den Kamera-Fokus unmittelbar verschieben (Das selbe Verhalten, wie bei map.gero.admin.ch)
- bei Datensätzen: Der Maus-Click bzw. das "Enter drücken" soll den ausgewählten Datensatz unmittelbar war an die oberste Position im Datenkatalog laden und anzeigen.

Siehe auch : [https://miro.com/app/board/uXjVLdk1g0o=/ (Suche)](https://miro.com/app/board/uXjVLdk1g0o=/?moveToWidget=3458764600478340467&cot=14)

**ToDos**
- [ ] Bitte ergänzen, falls spezielle ToDos beschreiben werden müssen

**Acceptance Criteria**
- [ ] Das erste Suchergebnis in der Ergebnisliste kann mitttels "Enter" direkt ausgewählt werden
- [ ] Bei Orten und Koordinaten verschiebt sich der Fokus der Kamera unmittelbar auf das ausgewählte Ergebnis
- [ ] Bei Datensätzen wird der ausgewählte Datensatz unmittelbar an der obersten Position des Datenkatalogs hinzugefügt.
- [ ] Bei der Auswahl aus der Ergebnisliste mit Maus oder Pfeil-Tasten sollen die Ergebnisse ebenfalls unmittelbar ausgewählt werden und  nach drücken von Enter dort hin navigiert werden.

**Hinweis**
- Quick Win aus UI/UX-Workshop 18.09.2024

**Comment by Anju023** [comment]
try this
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
If you don't have the c compliator, install it.(gcc or clang)

**Comment by nOester** [comment]
Testing 24.01.2025 auf https://dev-viewer.swissgeol.ch/

> - [x] Das erste Suchergebnis in der Ergebnisliste kann mitttels "Enter" direkt ausgewählt werden
> - [x] Bei Orten und Koordinaten verschiebt sich der Fokus der Kamera unmittelbar auf das ausgewählte Ergebnis
> - [x] Bei Datensätzen wird der ausgewählte Datensatz unmittelbar an der obersten Position des Datenkatalogs hinzugefügt.

Das folgende Feature sollten wir so anpassen, dass erst nach drücken der Entertaste zum ausgewählte Ort navigiert wird, da das unmittelbare verschieben der Kamera die 3D-Scene sehr unruhig macht.
> - [ ] Bei der Auswahl aus der Ergebnisliste mit Maus oder Pfeil-Tasten sollen die Ergebnisse ebenfalls unmittelbar ausgewählt werden und nach drücken von Enter dort hin navigiert werden

@daniel-va : Vor dem Deploy soll der obengenannte Punkt, so wie bereits bei der letzten Retro besprochen angepasst werden.
