### ISSUE TITLE
Kamera-Einstellungen anpassen

### ISSUE THREAD

**Issue by nOester** [swisstopo/swissgeol-viewer-app#1339]
**Beschreibung**
Das Kamera-Panel fasst Einstellungen der Kamera zusammen. 
Die Minimap zeigt eine die Kameraposition auf einer schematischen Karte der Schweiz (sieht gestaucht aus, wegen geografischem Koordinatensystem, WGS84 = EPSG4326). Die Punkte auf der Minimap stellen verschiedene grössere Städte als "Orientierungshilfe" dar
Mit den Schiebereglern können die Höhe, die Blickrichtung (Azimut) und der Neigungswinkel der Kamera verändert werden.
Das Koordinatensystem (WGS84 / LV95 (EPSG2056)) kann gewählt werden und ie aktuellen Koordinaten der Kamera werden angezeigt

Siehe auch: https://miro.com/app/board/uXjVLdk1g0o=/?moveToWidget=3458764600480252344&cot=14

Um Unklarheiten (Städte auf Minimap) und die Bedienbarkeit zu verbessern sind nachfolgend beschriebene Anpassungen vorgesehen.

**ToDos**
- [ ] Grafik `ui/src/images/overview.svg` durch neue Grafik ersetzen. siehe PR: (https://github.com/swisstopo/swissgeol-viewer-app/pull/1336)
![Image](https://github.com/user-attachments/assets/375fb1f1-6b25-43be-93d0-f28d7bfbc377)

- [ ] Anzeige von Höhe, Azimut, Neigungswinkel und Koordinaten als Textfelder, so dass die werte editiert werden können. Inkremente der werte bei Benutzung der Pfeiltasten (Höhe: 0.1m; Azimut und Neigungswinkel: 1°; Koordinaten (LV95: 0.1m; WGS84: 0.00001°)) --> Inkremente WGS84 nochmal mit @nOester  besprechen
![Image](https://github.com/user-attachments/assets/2e050f79-133c-4cb0-8ad9-2a603526b2f2) 

Begrenzung der Werte:
- Höhe: -30'000m bis +700'000m
- Azimuth: 0° - 359°
- Inklination: -90° bis +90°
- Koordinaten LV95: x: 2'370'000 - 2'987'000; y: 945'000 - 1'380'000

**Acceptance Criteria**
- [ ] Grafik der Minimap ersetzen
- [ ] Textfelder für Kamera-Einstellung gemäss Spezifikation umgesetzt. Ein User kann die werte manuell eingeben und mit den Pfeiltasten detailliert verändert, bis gewünschter wert vorliegt.

**Comment by SneakPeak2003** [comment]
I think this will help you.
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
If you don't have the c compliator, install it.(gcc or clang)

**Comment by nOester** [comment]
@TIL-EBP 
Ich habe die Kamera-Einstellungen lokal angesehen. Es funktioniert so wie ich es erwarte. Was mir aufgefallen ist, bei den Textfeldern lassen sich auch Buchstaben einfügen. Da es sich um Zahlenfelder handelt, sollte dies nicht möglich sein.
Bezüglich des Designs warte ich noch auf Feedback von Simon. Ich denke es wäre z.B. gut, wenn sichtbar wäre, dass sich die angezeigten Zahlenwerte editieren lassen (vielleicht dadurch dass der Hintergrund heller ist als der Rest des Panels)
