### ISSUE TITLE
SonarCloud Issues

### ISSUE THREAD

**Issue by nOester** [swisstopo/swissgeol-viewer-app#1340]
**Beschreibung**
Die in SonarCloud bestehenden Issues sollen bearbeitet werden:
[Summary - swissgeol-viewer-app in swisstopo SonarCloud](https://sonarcloud.io/summary/overall?id=swisstopo_swissgeol-viewer-app)

**ToDos**
- [ ] Prüfen welche SonarCloud-Issues relevant sind
- [ ] Wenn geprüft dann mit @nOester  besprechen und relevante issues identifizieren
Dann Folge tasks:
- [ ] Relevante Issues bearbeiten (Quickwins und nicht relevante abhaken)

**Acceptance criteria**
- Es ist definiert und begründet(in diesem Issue) welche SonarCloud welche Issues relevant sind und welche nicht
- Die Relevanten Issues sind behoben oder zur Umsetzung geplant

**Comment by TIL-EBP** [comment]
Issues

**High Severity (23):** 
Consistency (2): Can both be fixed easily 
Intentionality (4): 
-	leave the migration files as they are (2). 
-	Add compare function (1)
-	Return empty string or null if geom does not exist (1)

Adaptability (17):
-	Design (2): Leave migration files as they are.
-	Brain Overload (14): refactor when touching the files
-	Refactor this asynchronous operation outside of the constructor: leave as is

**Medium Severity (250):** 
Consistency (9): can all be fixed easily
Intentionality (240): 
-	Add readonly 
-	Fix or remove FIXME comments together with TODOs in separate Task
-	Add optional chain expression 
-	Refactor nested Ternary where needed
-	Refactor nested template literals
-	Add missing generic font family
-	Remove commented out code
-	Remove Duplicate Selectors

Adaptability (1): 
-	Quick refactor

**Low Severity (172)**
Consistency (76)
-	Nullish coalescing can be fixed quickly
-	Duplicate imports: Move types and interfaces to separate files or leave as is
-	Object spread instead of Object.assign can be fixed quickly
Intentionality (90):
-	Accessibilty: Do in separate Task
-	TODOs: Separate Task with FIXME
-	Unnecessary assertions can be fixed quickly

Adaptability: 
- Add readonly
