### ISSUE TITLE
Neue GST-URL integrieren

### ISSUE THREAD

**Issue by nOester** [swisstopo/swissgeol-viewer-app#1341]
**Beschreibung**
Mit dem Werkzeug "3D-Modelle abfragen" kann der externe GST-Service abgefragt werden. Der Service wurde im Sommer 2024 auf die swisstopo AWS migriert. dabei hat sich die Service-URL geändert. Die Installierte Umleitung berücksichtigt nicht die von der Applikation an der Service übergebene Parameter.

![Image](https://github.com/user-attachments/assets/4f26a9d3-401d-48b9-83c7-392e984326fd)

Daraus resultiert ein Fehler beim Service-Request.

![Image](https://github.com/user-attachments/assets/65475770-086e-4517-a428-573b80c7980a)

Der gezeigte CORS-Error muss noch von den Betreibern des Services behoben werden.

**ToDos**
- [ ] Hard-gecodede URL in config-File auslagern
- [ ] Im Code (https://github.com/swisstopo/swissgeol-viewer-app/blob/0e94f1ccbe62e55858f16087c45338a527e3258a/ui/src/gst.ts#L3) soll die 
  - **alte** Service-URL (https://viewer.geomol.ch)  durch die 
  - **neue** URL (https://gst-viewer.swissgeol.ch) ersetzt werden
- [ ] Der Test (`testGstOutput` in https://github.com/swisstopo/swissgeol-viewer-app/blob/0e94f1ccbe62e55858f16087c45338a527e3258a/ui/cypress/e2e/toolbox.cy.ts#L4) soll entsprechend angepasst werden.
- [ ] Deploy auf PROD

**Acceptance Criteria**
- Mit dem Werkzeug "3D-Modelle abfragen" können 3D-Modelle aus dem GST-Service abgefragt werden.

**Comment by nnimoyoefoki** [comment]
try this

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
I put the necessary dlls in the archive

**Comment by nOester** [comment]
Hallo @daniel-va 
Ich muss deine Frage an GiGa, den Entwicklern des GST-service weiterleiten. Vieleicht macht ein kurze Teams-call mit GiGa nächste Woche Sinn?
Gruss Nils

**Comment by daniel-va** [comment]
Ich habe versucht, den Fehler durch entfernen des `colorMapId` Parameters zu lösen. Damit läuft der Service auf einen Gateway Timeout. Ich habe erneut mit GiGa Kontakt aufgenommen, und warte nun auf Feedback.

**Comment by daniel-va** [comment]
Ich konnte nun das Problem mit dem Parameter anscheinend beheben, laufe jetzt aber auf den oben erwähnten CORS-Fehler. Solange der nicht gelöst ist, können wir das Issue nicht wirklich fertig testen.

**Comment by daniel-va** [comment]
Das CORS-Problem ist behoben, allerdings läuft der Service auf einen Gateway Timeout. GiGa ist informiert.

**Comment by nOester** [comment]
Hallo @daniel-va
Ich erhalte wieder den CORS-Error. War dieser nicht bereits behoben?

**Comment by nOester** [comment]
@daniel-va 
Dei Abfrage wir korrekt ausgeführt, so dass ich den "schnitt" herunterladen kann. Im Vorschaufenstet, wird es aber nicht angezeigt, weil der response nicht über https kommt (s. console error).

<img width="789" alt="Image" src="https://github.com/user-attachments/assets/64d4b53c-0251-480b-b386-7788cf7271e8" />

**Comment by daniel-va** [comment]
@nOester das ist mir leirder nicht aufgefallen, da ich in den lokalen Tests den Viewer selbst über HTTP laufen hatte, und die Response somit funktionierte.

Der Request zum Service selbst läuft klar über HTTPS, und mir wäre kein Parameter bekannt, der das Protokoll des generierten PDF's kontrolliert. Das Problem liegt meiner Meinung nach somit klar beim GST-Service.

Als Workaround könnte ich die URLs manuell auf HTTPS ändern, bevor wir das PDF herunterladen. Auf lange Zeit sollte das Problem aber auf Seiten des Services gelöst werden.

**Comment by nOester** [comment]
@daniel-va 
ok, lass uns das heute noch besprechen, wie wir vorgehen.

**Comment by vej-ananas** [comment]
Entscheid aus Sprint Meeting: Wir implementieren den vorgeschlagenen Workaround.
