### ISSUE TITLE
CI/CD - Pipeline harmonisieren

### ISSUE THREAD

**Issue by nOester** [swisstopo/swissgeol-viewer-app#1342]
**Beschreibung**
Die CI/CD-Pipeline des Viewers weicht von den der Applikationen "assets.swissgeol.ch" und "boreholes.swissgeol.ch" ab. Die Pipelines sollen vereinheitlicht werden, um den Betrieb zu vereinfachen.

**ToDos**
- [ ] Anpassungsmöglichkeiten bei der CI/CD-Pipeline von "viewer.swissgeo.ch" identifizieren
- [ ] Mit PO Anpassungsmöglichkeiten diskutieren
- [ ] CI/CD-Pipeline anpassen

**Acceptance Criteria**
- CI/CD-Pipeline von viewer.swissgeol.ch ist gemäss der definierten Anpassungen angepasst.
