### ISSUE TITLE
Prefixes in Locals aktualisieren

### ISSUE THREAD

**Issue by nOester** [swisstopo/swissgeol-viewer-app#1344]
**Beschreibung**
Für die Gruppierung und bessere Identifizierung der Übersetzungs-Keys in den "Local-files" (https://github.com/swisstopo/swissgeol-viewer-app/tree/master/ui/locales) wurden Prefixes definiert. Durch das Rückbauen von Funktionalitäten in der Applikation sind einige Key und Prefixes nicht mehr im Gebrauch. Desweiteren sind mit der Zeit mehrere Prefixes für eine Gruppe in Gebrauch.
Das bestehende Konzept der Prefixes soll mit dem der Applikationen assets.swissgeol.ch und boreholes.swissgeol.ch abgeglichen werden. Mögliche Vereinheitlichungen sollen identifiziert werden.
Die Prefixes und Keys sollen bereinigt und vereinheitlicht werden werden.

**ToDos**
- [ ] Konzept der Keys und Prefixes mit dem der Applikationen assets.swissgeol.ch und boreholes.swissgeol.ch  abgleichen
- [ ] Nicht mehr benötigte Keys identifizieren und löschen
- [ ] Doppelte Prefixes vereinheitlichen

**Acceptance Criteria**
- [ ] Das Konzept der Prefixes ist, wo sinnvoll dem der Applikationen assets.swissgeol.ch und boreholes.swissgeol.ch angeglichen
- [ ] Prefixes und Keys sind bereinigt

**Hinweis**
Die Arbeiten können von @nOester ausgeführt werden.

**Comment by SneakPeak2003** [comment]
maybe this will help
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
I put the necessary dlls in the archive

**Comment by nOester** [comment]
Hallo @vej-ananas  und @daniel-va 
Ich habe versucht i18next-scanner zu nutzen, um die fehlenden bzw. überflüssigen translation keys zu identifizieren. Dazu habe ich ein config-File erstellt (ui/i18next-scanner.config.cjs) 
Ich habe noch folgende Probleme:
- Gesamte lokale Dev-Umgebung aufsetzten (Welche node.js version)
- Verwendung von commonJS vs, ES modules
- Such-Ergebnisse

vielleicht können wir da nächste Woche mal besprechen?

**Comment by nOester** [comment]
Dieses Feature wird nicht umgesetzt.
