### ISSUE TITLE
Geometrien erstellen | Freeze

### ISSUE THREAD

**Issue by nOester** [swisstopo/swissgeol-viewer-app#1349]
**Beschreibung**
Bei der Bearbeitung von Geometrien (z.B. beim Zeichnen von Linien) blockiert die Funktion, wenn eine gezeichnete Linie unmittelbar nach der Erstellung an den "Griffpunkten" verändert wird.
Nach einem Reload kann die Linie problemlos editiert werden.

Siehe Screencast: https://github.com/user-attachments/assets/f23ae19f-cb22-4ace-9176-b950cebfdb98

Bei folgenden Geometrietypen tritt das fehlerhaft verhalten nicht auf:
- Punkte
- Polygone
- Rechtecke (Bei kleinen Rechtecken kommt es ab dem Unterschreiten einer bestimmten Distanz der Eckpunkte dazu, das die Form Recktecks vollständig verändert wird --> Folgetask: #1354)
![Image](https://github.com/user-attachments/assets/0d0fcea4-510f-48dd-b044-7f5e6a0a1bfc)
![Image](https://github.com/user-attachments/assets/969dc549-0d1a-4807-9e27-7d371f2be538)

**ToDos**
- [ ] Prüfen warum das Editieren der Liniengeometrie nach der Erstellung blockiert
- [ ] Behebung des Blockieren, so dass eine Geometrie, unabhängig vom Zeitpunkt, funktioniert

**Acceptance Criteria**
- [ ]  Das Editieren einer Geometrie funktioniert fehlerfrei, ohne Blockieren.
