### ISSUE TITLE
Grosse files aus Repo entfernen

### ISSUE THREAD

**Issue by nOester** [swisstopo/swissgeol-viewer-app#1350]
**Beschreibung**
Es gibt grosse Files im Repository.  Diesen befinden sich der Commit-History und sollen entfernt werden. Ziel ist die Grösse des Repositories zu verkleinern und das Repository zu bereinigen. Die gesamte Commit-History soll in einem Backup erhalten bleiben. 

**ToDos**
- [x] @nOester : Soll das Repo umbenannt werden? --> Das Repository auf den Namen `swissgeol-viewer-suite` geändert werden, damit der Name konsistent mit denen der anderen Applikationen ist.
- [x] Erstelle ein Backup, entferne die grossen Files > 50MB aus dem Repo und force pushe.
- [x] Stelle sicher, dass alle anderen Benutzer eine saubere Kopie des Repos danach benutzen.
- [x] Sämtliche lokale Versionen des Repsoitories müssen vor den weiteren Entwicklungen aktualisiert werden

**Acceptance Criteria**
- [x] Die grossen Files sind nicht mehr im Repository vorhanden

**Comment by vej-ananas** [comment]
Es war ausreichend, drei nicht-gemergte Branches zu löschen. In diesen Branches wurden grosse Files hinzugefügt und entfernt in verschiedenen Commits:

- GSNGM-191-exaggeration-branch-2
- GSNGM-191-tiles-exaggeration   
- test_voxel-render-order
