### ISSUE TITLE
ION.defaultAccessToken in Config auslagern

### ISSUE THREAD

**Issue by nOester** [swisstopo/swissgeol-viewer-app#1351]
**Beschreibung**
Der AccessToken, mit dem Daten von Cesium-ION  in die Viewer-Applikation integriert werden, ist im Code hard-codiert. Der AccessToken soll in ein Config-File (z.B. env) ausgelagert werden.

Der Token ist an folgenden Stellen im Code hinterlegt:
[Cesium-ION AccesTokens ](https://github.com/search?q=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI0YjNhNmQ4My01OTdlLTRjNmQtYTllYS1lMjM0NmYxZTU5ZmUiLCJpZCI6MTg3NTIsInNjb3BlcyI6WyJhc2wiLCJhc3IiLCJhc3ciLCJnYyJdLCJpYXQiOjE1NzQ0MTAwNzV9.Cj3sxjA_x--bN6VATcN4KE9jBJNMftlzPuA8hawuZkY&type=code)

Der Token besitzt folgende Rechte: 
Access
This token provides access to the following scopes:
- assets:list
- assets:read
- assets:write
- geocode

**ToDos**
- [x] Prüfen, ob der Token Schreibberechtigungen benötigt. wenn nicht kann das entsprechende Recht dem Token entzogen werden.
- [ ] AccessToken in ein Config-File auslagern. Es gibt eine Datei in der Konstanten gespeichert werden ([ui/src/constants.ts](https://github.com/swisstopo/swissgeol-viewer-app/blob/master/ui/src/constants.ts)), vielleicht könnten wir diese Daten auch für den cesium ion AccessToken nutzen?

**Acceptance Criteria**
- [ ] AccessToken ist in ein Config-File auslagert und die Daten von Cesium-ION werden korrekt angezeigt

**Comment by nOester** [comment]
@vej-ananas @daniel-va 
Ich habe beim aktuellen AccessToken die schreibrechte entfernt und auf der produktiven Applikation getestet. Aus meiner Sicht sind die Schreibrechte nicht erforderlich. Wir können daher mit dem bestehenden Token weiterfahren.
