### ISSUE TITLE
Ermögliche das Ausführen der Entwicklungsumgebung auf Windows

### ISSUE THREAD

**Issue by nOester** [swisstopo/swissgeol-viewer-app#1353]
**Beschreibung**
Zurzeit lässt sich die Entwicklungsumgebung unter Windows nicht ausführen. Die Entwicklungsumgebung, so soll aufgebaut werden, dass sie sowohl unter Linux, als auch Windows lauffähig wird.
die Delpoy-Scripte liegen momentan nur als .sh vor, damit lassen sihc sie nicht unter Windows ausführen. 
Als ersten Schritt kann git-bash benutzt werden, falls die Implementierung simpel ist.

**ToDos**
- [ ] Prüfen, wie die Umwicklungsumgebung unter Windows und Linux ausführbargemacht werden kann. Ist ein gemeinsames Vorgehen möglich oder müssen separate Prozesse definiert werden, die auch im Readme.md dokumentiert werden vgl. #1343
- [ ] Anpassung der nötigen Skripte, um Umgebung unter Linux und Windows ausführen zu können

**Acceptance Criteria**
- [ ] Entwicklungsumgebung ist unter Linux und Windows ausführbar
