### ISSUE TITLE
Sidebar & Headeranpassen

### ISSUE THREAD

**Issue by nOester** [swisstopo/swissgeol-viewer-app#1361]
**Beschreibung**
Die Sidebar soll gemäss der UI-definition in Figma (https://www.figma.com/design/cEiOoOazAQZqpRY92ZhBeO/swissgeol?node-id=9583-8200)

**ToDos**
- [ ] Reihenfolge der Icon anpassen
- [ ] Symbole ändern
- [ ] "Tooltip" inetrgieren
- [ ] Login-Button anpassen
- [ ] Language-Switcher anpassen
- [ ] Suchfeld anpassen
- [ ] Gap zwischen Login - Language-Switcher und Koordinaten/Terrain vergrössern. Grundsätzlich aber rechts belassen

**Acceptance Criteria**
- [ ] Die Sidebar entspricht in Ansehen und Funktion den Definitionen im oben verlinkten Figma.

**Comment by TIL-EBP** [comment]
@nOester das Ticket heisst zwar Sidebar & Header anpassen, aber in der Beschreibung wird nur von der Sidebar gesprochen, nicht vom Header. In welchem Ticket wird der Header angepasst? Hier oder in #1338 oder nochmals in einem anderen?

**Comment by nOester** [comment]
@TIL-EBP 
Danke für dein Hinweis. Ja, dass ist nicht ganz konsistent. Ich würde die Headeranpassungen in diesem Ticket machen. Ich ergänze die Beschreibung dementsprechend. Wir können uns sonst gerne heute Vormittag diesbezüglich austauschen.

**Comment by nOester** [comment]
Testing 27.01.2025  auf https://dev-viewer.swissgeol.ch/

> - [x] Reihenfolge der Icon anpassen
> - [x] Symbole ändern
> - [ ] "Tooltip" intergieren
> - [ ] Login-Button anpassen
> - [ ] Language-Switcher anpassen
> - [ ] Suchfeld anpassen
> - [ ] Gap zwischen Login - Language-Switcher und Koordinaten/Terrain vergrössern. Grundsätzlich aber rechts belassen

**Comment by vej-ananas** [comment]
Das Springen der Koordinaten wird durch #1428 gelöst
