### ISSUE TITLE
Cesium Tool Einstellungen auswählen

### ISSUE THREAD

**Issue by nOester** [swisstopo/swissgeol-viewer-app#1362]
**Beschreibung**
Aktuell enthalt die Cesium Toolbar verschiedene Einstellungen mit denen die Darstellung und das Verhalten des cesium-Globus beeinfluss werden kann. Die Funktionsweise und Auswirkung der Einstellungen ist nicht immer klar ersichtlich. Daher soll eine Auswahl von Einstellungen getroffen werden. Die ausgewählten Einstellungen sollen in den Viewer (Einstellungs-Tab in "Angezeigte Daten", (https://www.figma.com/design/cEiOoOazAQZqpRY92ZhBeO/swissgeol?node-id=9583-8200)) integriert und dokumentiert werden. 

Die Dokumentation ist nicht Teil dieses Tasks. Der Ort der Dokumentation ist noch zu definieren. Die Dokumentation sollte so aufgebaut werden, dass sie bei jeder Einstellung im UI abgerufen werden kann.

**ToDos**
- [ ] Cesium Toolbar Einstellungen auswählen
- [ ] Einstellungen in Einstellungs-Tab in "Angezeigte Daten integrieren

**Acceptance Criteria**
- [ ] Ausgewählte Einstellungen sind gemäss oben verlinktem Figma integriert
