### ISSUE TITLE
About-Panel anpassen

### ISSUE THREAD

**Issue by nOester** [swisstopo/swissgeol-viewer-app#1363]
**Beschreibung**
In der Sidebar ist unter dem "Zahnradsymbol" das Impressum und die Cesium-Toolbar platziert.
Gemäss Figma (https://www.figma.com/design/cEiOoOazAQZqpRY92ZhBeO/swissgeol?node-id=9583-8200) soll das Symbol gewechselt und das Name des Panels von "Einstellungen" in "Über" gewechselt werden. Des weiteren sollen in diesem Panel die Cesium-Toolbar entfernt werden. Zukünftig kann neben dem Impressum auch eine Beschreibung der verwendeten SW-Libraries, so wie bei der Applikation boreholes (Settings> About) integriert werden. 

**ToDos**
- [ ] Symbol wechseln
- [ ] Titel ändern (Translation files)
- [ ] cesium-Toolbar entfernen

**Acceptance Criteria**
- [ ] Design entspricht der Definition in oben verlinktem Figma
