### ISSUE TITLE
Struktur Datenkatalog an map.geo.admin anpassen

### ISSUE THREAD

**Issue by nOester** [swisstopo/swissgeol-viewer-app#1364]
**Beschreibung**
Der bestehende Datenkatalog soll soweit wie möglich an den Datenkatalog des Themas "Geologie" in map.geo.admin.ch (https://map.geo.admin.ch/#/map?lang=de&center=2660000,1190000&z=1&bgLayer=ch.swisstopo.pixelkarte-grau&topic=geol&layers=&catalogNodes=geol) angepasst werden

**ToDos**
- [ ] Konzept des Datenkatalogs basierend of dem datenakatalog von map.geo.admin ist erstellt
- [ ] Datenkatalog entspricht dem des Themas "Geologie" in map.geo.admin.ch (Hauptkategorien)

**Acceptance Criteria**
- [ ] Datenkatalog entspricht dem oben definieten Konzept
