### ISSUE TITLE
Struktur Datenpanel anpassen

### ISSUE THREAD

**Issue by nOester** [swisstopo/swissgeol-viewer-app#1366]
**Beschreibung**
Der "Datenpanel" soll gemäss https://www.figma.com/design/cEiOoOazAQZqpRY92ZhBeO/swissgeol?node-id=9583-8200&node-type=canvas&t=tILxT5WWVXi9FzqU-0 nue strukturiert werden.

**ToDos**
- [ ] Hintergrundkarte und aus dem Datenkatalog selektierte Datensätze ("Layer") im oberen Bereich des Panel platzieren
- [ ] Datenkatalog im unteren Bereich des Panels platzieren

**Acceptance Criteria**
- [ ] Struktur des Panel entspricht dem oben verlinkten Figma

**Comment by nOester** [comment]
Testing 24.01.2025 auf https://dev-viewer.swissgeol.ch/

> - [x] Hintergrundkarte und aus dem Datenkatalog selektierte Datensätze ("Layer") im oberen Bereich des Panel platzieren

> - [x] Datenkatalog im unteren Bereich des Panels platzieren

@daniel-va: Kann so deployed werden.

Die Struktur so passt mit Figma, die Farbgebung und Gestaltung der einzelnen Layer entspricht noch dem alten Design. Ist die Anpassung im #1371 vorgesehen?
