### ISSUE TITLE
Disclaimer umbauen

### ISSUE THREAD

**Issue by nOester** [swisstopo/swissgeol-viewer-app#1375]
**Beschreibung**
Der bestehende Disclaimer soll entsprechend der Definition in Figma: https://www.figma.com/design/cEiOoOazAQZqpRY92ZhBeO/swissgeol?node-id=9598-111197&node-type=section&t=EyWoIe28GOV1xAbK-0 umgebaut werden.

**ToDos**
- [ ] Umbau bestehender Disclaimer in die in Figma (s. oben) definierte Form. Der Text des Disclaimers ist im translation-key `"tracking_text"` der jeweilgen Übersetzungs-files in https://github.com/swisstopo/swissgeol-viewer-app/tree/develop/ui/locales

**Acceptance Criteria**
- [ ] Disclaimer entspricht der Definition in Figma (s. oben)

**Comment by nOester** [comment]
Testing 24.01.2025 auf https://dev-viewer.swissgeol.ch

- [x] Disclaimer entspricht der Definition in Figma (s. oben)

Kann so deployed werden.

Übergeordnete Frage, die beim Testen aufgekommen ist. Die im Farben definierten Farben sind zum Teil schwer unterscheidbar und zum anderen "beissen" sie sich (Button enables <-> Button active). Das ist eine Thema, das ich mit  Simon besprechen werde.
