### ISSUE TITLE
Targetpoint | Blaue Achse wechselt Orientierung

### ISSUE THREAD

**Issue by nOester** [swisstopo/swissgeol-viewer-app#1394]
**Beschreibung**
Der Targetpoint kann mit dem im folgenden Screenshot dargestellten roten "Stern" aktiviert werden
![Image](https://github.com/user-attachments/assets/4036ed1e-7f84-4ce0-817d-19bc68379adf)

Beim Heranzoomen an den Targetpoint (Mouserad) wird bis zu einer bestimmten Distanz zum Targetpoint die blaue Achse nach oben angezeigt:
![Image](https://github.com/user-attachments/assets/f2e3126e-6300-41bf-9e8d-ef5cd44fbeaf)

Beim Unterschreiten einer bestimmten Distanz zeigt die blaue Achse nach unten: 
![Image](https://github.com/user-attachments/assets/17c467b1-4223-451f-bee3-3d3ac10f4eac)

Die blaue Achse sollte unabhängig von der Distanz immer nach oben zeigen.

**ToDos**
- [ ] Untersuchen warum die Orientierung der blauen Achse wechselt
- [ ] Falls eine einfache Lösung nicht möglich ist, weiteres Vorgehen mit @nOester besprechen
- [ ] Wenn einfache Lösung möglich, Code so anpassen, dass die blaue Achse immer nach oben zeigt

**Acceptance Criteria**
- [ ] Blaue Auchse des Targetpoints zeigt immer nach oben

**Comment by nOester** [comment]
Auf #1590 warten. dann entschieden, wie es hier weitergeht.
