### ISSUE TITLE
Slicingbox bei Überhöhung | Verhalten anpassen

### ISSUE THREAD

**Issue by nOester** [swisstopo/swissgeol-viewer-app#1396]
**Beschreibung**
Bei Überhöhen einer 3D-Szene zeigt die Slicingbox folgendes Verhalten.
- Die Pfeile zum Verändern der Grösse der Slicingbox werden unsichtbar
- Die Slicingbox scheint nicht überhöht zu werden

Nicht überhöht, Pfeile sind sichtbar.
![Image](https://github.com/user-attachments/assets/0919689c-5013-4c5e-9463-c9e4016e9bd3)

Überhöht, Pfeile sind nicht sichtbar und  Slicingbox ist nicht überhöht:
![Image](https://github.com/user-attachments/assets/c90e7dea-c5c7-4e65-8939-54691d58f777)

**ToDos**
- [ ] Code so anpassen, dass die Pfeile unabhängig von der Überhöhung sichtbar sind. Aussnahme transparente Slicingbox wird deaktiviert
- [ ] Die Slcingbox wird zusammen mit ihrem Inhalt überhöht

**Acceptance Criteria**
- [ ] Pfeile an der Slicingbax sind unabhängig von der Überhöhung sichtbar.
- [ ] Die Slcingbox wird zusammen mit ihrem Inhalt überhöht

**Comment by TIL-EBP** [comment]
@nOester ich habe etwas gebraucht um das Problem zu identifizieren. Die Pfeile, die dargestellt werden, sind custom 3D Modelle, die in .glb Files abgelegt sind. Diese scheinen Mühe zu haben, wenn man das Terrain überhöht, da dann irgendwelche Berechnungen schief gehen. 

Ich habe die Pfeile zum testen mal durch einfache Würfel ersetzt (Cesium-eigene Entities), und dann funktioniert die Darstellung korrekt, auch bei Überhöhung. Nun gibt es die Möglichkeit, die Pfeile in Cesium nachzubauen, ohne externe Files zu verwenden. Ist das für dich in Ordnung?

**Comment by nOester** [comment]
Hallo @TIL-EBP 
Das hört sich für mich sinnvoll an. Wie gross ist der Aufwand? Benutzt due Entities mit denen du die Pfeile erstellst?

**Comment by nOester** [comment]
@TIL-EBP 
Ok, dann lass uns so weitermachen.

**Comment by nOester** [comment]
@TIL-EBP 
Besteht die Möglichkeit die Pfeile zu scalieren, so dass sie bei allen Zoom-Levels die gleiche Grösse behalten?

![Image](https://github.com/user-attachments/assets/ab2aafd2-a8ea-46c9-9c47-ef3a8e969b98)

Wenn man jetzt in die Szene hineinzoomt, vergrössern sich die Pfeile so stark; dass sie sehr dominant sind.

**Comment by TIL-EBP** [comment]
@nOester das ist wirklich nicht sehr schön, ich schaue es mir gleich an

**Comment by TIL-EBP** [comment]
@nOester  in [diesem PR](https://github.com/swisstopo/swissgeol-viewer-app/pull/1490) habe ich jetzt die Grösse der Pfeile anhand der Distanz zur Kamera angepasst. Das heisst, sie verändern ihre grösse je nach dem, wie weit man rausgezoomt hat. 
Die einzelnen Werte (wie grosse sie mindestens und maximal sind) können noch etwas kalibriert werden. 
Willst du es dir mal anschauen? Im `constants.ts` File kannst du auch mit den Werten spielen um zu sehen wie es sich verändert.

**Comment by TIL-EBP** [comment]
@nOester 
Das liegt nicht an der Überhöhung selber, sondern daran, dass die Geometrien irgendwann nicht mehr dargestellt werden. Das war auch schon vorhin der Fall. Wenn du auf [viewer](https://viewer.swissgeol.ch/) gehst und dort eine Slicing Box machst und diese dann nach unten erweiterst, verschwindet irgendwann der Pfeil. Dasselbe nun auf [dev-viewer](https://dev-viewer.swissgeol.ch/). Da kannst du sogar sehen, wie die einzelnen Elemente, aus denen der Pfeil besteht, nach und nach verschwinden. Was genau der Grund dafür ist, weiss ich nicht und konnte ich auf die schnelle auch nicht finden. Kann das aber nachschauen. Ich würde allerdings ein neues Ticket dafür aufmachen, da es ja ein andere Bug ist

**Comment by nOester** [comment]
Ich werde ein neuen Ticket erstellen.
Darin können wir auch die heute am Tel. aufgekommenen Fragen klären
- Definieren wir eine minimale Grösser einer Slicingbox?
- Behalten wir die Funktionalität bei, dass wir das ab der minimalen Breite (aktuelle 450m) die Box in Pfeilrichtung bewegt wird?
-

**Comment by nOester** [comment]
Folge-isuue: #1502
